# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cUPRhVjC8wPAwqZuT6H4bkyv2nJYUCZf
"""

# =====================================================
# E-commerce Return Rate Reduction Analysis
# Data Cleaning
# =====================================================

# -------------------------------
# Import Libraries
# -------------------------------
import pandas as pd
import numpy as np

# -------------------------------
# Load Dataset
# -------------------------------
df = pd.read_csv("ecommerce_dataset.csv")

# -------------------------------
# Basic Exploration
# -------------------------------
print("="*60)
print("INITIAL DATASET OVERVIEW")
print("="*60)

print(f"\nDataset Shape : {df.shape}")

print("\nFirst 5 Rows:")
print(df.head())

print("\nDataset Information:")
print(df.info())

print("\nSummary Statistics:")
print(df.describe(include='all'))

# -------------------------------
# Missing Values Before Cleaning
# -------------------------------
print("\nMissing Values Before Cleaning:")
print(df.isnull().sum())

# -------------------------------
# Duplicate Check
# -------------------------------
duplicates = df.duplicated().sum()
print(f"\nDuplicate Rows : {duplicates}")

if duplicates > 0:
    df = df.drop_duplicates()

print(f"Dataset Shape After Removing Duplicates : {df.shape}")

# -------------------------------
# Remove Extra Spaces
# -------------------------------
object_cols = df.select_dtypes(include='object').columns

for col in object_cols:
    df[col] = df[col].astype(str).str.strip()

# -------------------------------
# Convert Date Columns
# -------------------------------
date_columns = [
    "order_date",
    "delivered_date",
    "request_date"
]

for col in date_columns:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors='coerce')

# -------------------------------
# Standardize Text Columns
# -------------------------------
# Re-identify object columns after date conversion
object_cols = df.select_dtypes(include='object').columns

for col in object_cols:
    df[col] = df[col].str.title()

# -------------------------------
# Standardize Returned Column
# -------------------------------
if "returned" in df.columns:
    df["returned"] = (
        df["returned"]
        .replace({
            "Yes": "Yes",
            "No": "No",
            "Y": "Yes",
            "N": "No"
        })
    )

# -------------------------------
# Fill Missing Numerical Values
# -------------------------------
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

# -------------------------------
# Handle Return Reason Separately
# -------------------------------
if "returned" in df.columns and "return_reason" in df.columns:

    # Orders not returned
    df.loc[df["returned"] == "No", "return_reason"] = "No Return"

    # Returned orders with missing reason
    mode_reason = df.loc[
        df["returned"] == "Yes",
        "return_reason"
    ].mode()

    if not mode_reason.empty:
        df.loc[
            (df["returned"] == "Yes") &
            (df["return_reason"].isna()),
            "return_reason"
        ] = mode_reason[0]

# -------------------------------
# Fill Remaining Categorical Values
# -------------------------------
categorical_cols = df.select_dtypes(include='object').columns

for col in categorical_cols:

    if col == "return_reason":
        continue

    mode = df[col].mode()

    if not mode.empty:
        df[col] = df[col].fillna(mode[0])

# -------------------------------
# Missing Values After Cleaning
# -------------------------------
print("\nMissing Values After Cleaning:")
print(df.isnull().sum())

# -------------------------------
# Verify Data Types
# -------------------------------
print("\nFinal Data Types:")
print(df.dtypes)

# -------------------------------
# Final Dataset Information
# -------------------------------
print("\nFinal Dataset Shape:", df.shape)

print("\nFinal Dataset Information:")
print(df.info())

# -------------------------------
# Verify Duplicate Rows
# -------------------------------
print("\nDuplicate Rows After Cleaning:")
print(df.duplicated().sum())

# -------------------------------
# Save Cleaned Dataset
# -------------------------------
df.to_csv("cleaned_ecommerce_dataset.csv", index=False)

print("\n" + "="*60)
print("DATA CLEANING COMPLETED SUCCESSFULLY")
print("="*60)
print("Cleaned dataset saved as:")
print("cleaned_ecommerce_dataset.csv")